{
    targets: {
        clean: {
            phony: true,
            run: "cat .gitignore | xargs rm -rf"
        },
        all: {
            phony: true,
            dependencies: ['build/*'],
            run: "ln -sfr static/* build/"
        },
        'build/editor.js': {
            dependencies: [
                "core/*",
                "ui/*"
            ],
            run: [
                "mkdir -p build",
                "pnpm exec esbuild core/index.ts --outdir=build  --bundle --sourcemap --splitting --platform=browser --format=esm --loader:.lpf=file",
                "mv build/index.js build/editor.js"
            ]
        },
        'build/ext/circuit.js': {
            dependencies: [
                "src/circuit/*.ts",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/circuit/ext.ts --outfile=build/ext/circuit.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file"
        },
        'build/ext/theme/default.js': {
            dependencies: [
                "src/themes/default.js",
                "build/editor.js"
            ],
            run: "mkdir -p build/ext/theme && ln -sfr src/themes/default.js build/ext/theme/default.js"
        },
        'build/ext/document.js': {
            dependencies: [
                "src/document/*.ts+",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/document/ext.tsx --outfile=build/ext/document.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file"
        },
        'build/ext/overview.js': {
            dependencies: [
                "src/overview/*.ts+",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/overview/ext.tsx --outfile=build/ext/overview.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file"
        },
        'build/ext/find-action.js': {
            dependencies: [
                "src/ui/find-action.jsx",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/ui/find-action.jsx --outfile=build/ext/find-action.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file"
        },
        'build/ext/chain-view.js': {
            dependencies: [
                "src/chain-view/*.ts",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/chain-view/ext.tsx --outfile=build/ext/chain-view.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file --loader:.css=text"
        },
        'build/ext/tree-view.js': {
            dependencies: [
                "src/tree-view/*.tsx",
                "build/editor.js"
            ],
            run: "pnpm exec esbuild src/tree-view/ext.tsx --outfile=build/ext/tree-view.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file --loader:.css=text"
        },
        'build/ext/chain_select.js': {
            dependencies: [
                "src/chain-view/tools/select.ts",
                "build/ext/chain.js"
            ],
            run: [
                "mkdir -p build/ext",
                "pnpm exec esbuild src/chain-view/tools/select.ts --outfile=build/ext/chain_select.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file --loader:.css=text"
            ]
        },
        'build/ext/chain_activate.js': {
            dependencies: [
                "src/chain-view/tools/activate.ts",
                "build/ext/chain.js"
            ],
            run: [
                "mkdir -p build/ext",
                "pnpm exec esbuild src/chain-view/tools/activate.ts --outfile=build/ext/chain_activate.js --bundle --sourcemap --platform=browser --format=esm --loader:.lpf=file --loader:.css=text"
            ]
        }
    }
}
